### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by hallelujahbaby** [kaishin/Gifu#86]
I got this error while using Carthage, please help, thanks a lot :)

*** Fetching Gifu
*** Checking out Gifu at "v1.2.1"
Parse error: expected submodule commit SHA in output of task (ls-tree -z v1.2.1 Carthage/Checkouts/Runes) but encountered:

**Comment by chickdan** [comment]
Here is how I got around the issue: 

1. If you are using other libraries remove Gifu from your cartfile. Then run "carthage update" so that you can checkout and build all of the other libraries without error.
2. Put Gifu back into the cartfile, run "carthage update" and wait for it to error out. 
3. Run "carthage checkout Gifu"
4. Go into the checkouts folder, go into the Gifu folder, delete the .gitmodules file (you may need to enable hidden files to see this file)
5. run "carthage build Gifu"

**Comment by kaishin** [comment]
From the looks of it this is related to the way Carthage works. See here for similar cases: https://github.com/Carthage/Carthage/issues/135

I will close this for now but happy to re-open in case something needs to be changed on Gifu.
